name: Build and SonarQube Scan

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube Analysis
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Lấy toàn bộ lịch sử git để có kết quả phân tích chính xác hơn

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Sử dụng Eclipse Temurin JDK
          java-version: '17'

      - name: Cache SonarQube Scanner
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: sonar-scanner-cli-${{ runner.os }}

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build project (Gradle)
        run: ./gradlew build

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Clean up workspace
        run: ./gradlew clean
